import "./globals.css";

import dynamic from "next/dynamic";
import { Inter } from "next/font/google";
import ClientProviders from "@components/providers";

import { Toaster } from "@ui/toaster";
import { Header } from "@/components/layout/header";
import { TailwindIndicator } from "@/components/tailwind-indicator";

const ThemeProvider = dynamic(() => import("@components/theme-provider"), {
  ssr: false,
});

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClientProviders>
          <ThemeProvider>
            <Header />
            {children}
          </ThemeProvider>
        </ClientProviders>
        <Toaster />
        <TailwindIndicator />
      </body>
    </html>
  );
}
