import { ThemeProvider } from "@/components/theme-provider";
import "./globals.css";
import { Inter } from "next/font/google";
import { TailwindIndicator } from "@/components/tailwind-indicator";
import { Header } from "@/components/layout/header";
import { Toaster } from "@ui/toaster";
import { SessionProvider } from "@components/providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <SessionProvider>
            <Header />
            {children}
          </SessionProvider>
        </ThemeProvider>
        <Toaster />
        <TailwindIndicator />
      </body>
    </html>
  );
}
